### ISSUE TITLE
Security Risks

### ISSUE THREAD

**Issue by TotalTechGeek** [jaydenwindle/senv#1]
Hi! I was browsing recently published packages and wanted to bring a few things to your attention (I realize that this is a new repository and that you might already be aware of these things).

## 1) You should set your initialization vectors. 

CBC without a unique initialization vector poses the same risks as using the AES-256 in ECB mode. 

The IV doesn't need to be kept secret, so you can append it to the beginning of your encrypted payload. 

Realistically, environment files aren't long / repetitive enough to pose much of a security risk, but correcting this would remove a few potential attack vectors. 

## 2) You need to authenticate the integrity of your decrypted data.

If someone is able to deduce just some of the contents of your encrypted file, they will be able to tamper with it. This could potentially allow them to swap out some of your tokens, allowing them to intercept your outgoing traffic. (This exact type of attack was used to coerce information out of [PGP encrypted emails](https://efail.de/))

You can easily append an HMAC to your output to be used to verify the integrity of your encrypted data. 

#### Note: You could actually kill two birds with one stone here: you can actually safely use a truncated HMAC as your Initialization Vector.  

It also gives you the benefit of being able to detect when you've typed in the wrong password without your code crashing after processing white noise.

## 3) You haven't implemented a key derivation algorithm (KDF). 

This is fine if you can guarantee the passwords being used have over 100 bits of entropy, (use [zxcvbn](https://www.bennish.net/password-strength-checker/) to measure), but if they aren't, it'll be much faster to brute-force potential passwords which severely undermines your security.

You'd likely want to implement [scrypt](https://www.npmjs.com/package/scrypt), [bcrypt](https://www.npmjs.com/package/bcrypt), or [argon2](https://www.npmjs.com/package/argon2) to mitigate the risk of someone brute-forcing passwords.

## 4) Passwords & sensitive data should almost never be command line arguments.

Unless you are on a single user machine, this carries a huge risk of leaking the password to other users of the system. 

If you're on a *nix-based machine, it'll likely commit the password to your command history, and worse, it'll be passed into the process table (which could allow other users the opportunity to view it).

You could instead allow them to pass the secret from a file (both *nix and Windows are designed to allow you to protect files from other users).

**Comment by jaydenwindle** [comment]
Thanks for the issue - that was really quick!

These are really good points. I'll address them as soon as I can.

**Comment by jaydenwindle** [comment]
@TotalTechGeek I've merged in a few PRs that address the issues you raised, so I'm going to close this issue. 

If you think there are still security risks in this implementation that need to be addressed, please let me know and I will re-open it.

Thanks again!

**Comment by TotalTechGeek** [comment]
Just submitted a PR :P
