### ISSUE TITLE
Does not work across operating systems

### ISSUE THREAD

**Issue by ElasticBottle** [jaydenwindle/senv#23]
The encrypted output from windows is not able to be decrypted by mac and vice versa

**Comment by arcoraven** [comment]
Looks like Mac and Windows have different ways of representing newline or carriage return. Try removing any trailing newlines from your `.env.pass` file since they'll be interpreted as different "passwords" depending on the OS.

**Comment by ElasticBottle** [comment]
Wow, thanks, saved me a ton of headache
